### PR TITLE
[WIP] Migrate to HAL+RTFM

### PR DESCRIPTION
**Pull request by dotcypress**
@Nercury I started porting example to RTFM+HAL using my `stm32g030` dev board, seems working fine 😄 
Could you try it on the actual crab? 

PS: Use `release` build, cause `debug` binary doesn't fit into the chip.

### CODE REVIEW

**Comment by Nercury** [comment]
Hi, this looks amazing. I am at work right now and I don't have necessary
crabware, but I will try it at home (8 hours later).

2019-11-14, kt, 07:43 Vitaly Domnikov <notifications@github.com> rašė:

**Comment by Nercury** [comment]
Would you mind of sharing your permanent address? I would ship you one of
the crabs. It would take around 10-14 days to arrive though.

2019-11-14, kt, 10:47 Nerijus <nercury@gmail.com> rašė:

**Comment by dotcypress** [comment]
@Nercury see DM on twitter

**Comment by Nercury** [comment]
Success: https://twitter.com/nercury/status/1195412290398502912

**Pull request merged**
